title: aznets
description: Machine Learning
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
is_user_page: true
github:
  ml_url: https://aznets.github.io/ml/
  dl_url: https://aznets.github.io/dl/
